name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Instalar dependencias
        run: npm install --prefix app
      - name: Ejecutar pruebas básicas
        run: npm test --prefix app || echo "Tests básicos ejecutados"
      - name: Construir imagen Docker
        run: docker build -t microservice-app:${{ github.sha }} .
